# Используем официальный образ Node.js
FROM node:18-alpine

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальной код приложения
COPY . .

ARG MONGODB_URI
ARG NEXTAUTH_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXTAUTH_URL_INTERNAL 
ARG NEXTAUTH_SECRET
ARG EMAIL_USER
ARG EMAIL_PASS
ARG UPLOADTHING_SECRET
ARG UPLOADTHING_APP_ID
ARG I18NEXUS_API_KEY
ARG NEXT_PUBLIC_RECAPTURE_1
ARG RECAPTURE_2

ENV MONGODB_URI=$MONGODB_URI
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV NEXTAUTH_URL_INTERNAL=$NEXTAUTH_URL_INTERNAL 
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV EMAIL_USER=$EMAIL_USER
ENV EMAIL_PASS=$EMAIL_PASS
ENV UPLOADTHING_SECRET=$UPLOADTHING_SECRET
ENV UPLOADTHING_APP_ID=$UPLOADTHING_APP_ID
ENV I18NEXUS_API_KEY=$I18NEXUS_API_KEY
ENV NEXT_PUBLIC_RECAPTURE_1=$NEXT_PUBLIC_RECAPTURE_1
ENV RECAPTURE_2=$RECAPTURE_2

# Собираем приложение Next.js
RUN npm run build

# Открываем порт, на котором будет работать приложение
EXPOSE 3000

# Запускаем приложение
CMD ["npm", "start"]